### PR TITLE
ドキュメントの維持管理や更新周期に関する言及

### PR DESCRIPTION
**Pull request by sankero**
以下のイシューについてPRを作成しました。
https://github.com/edash-product/edash-engineer-team-policy/issues/5

### CODE REVIEW

**Review by t-ikedash — APPROVED** [review]
DALL·E 2023-11-08 20 11 18 - Design a small digital badge of 500 pixels or less, featuring the acronym 'LGTM' in a golden hue at the center, symbolizing appreciation  Above 'LGTM'

**Review by k-takeuchi220 — APPROVED** [review]
5f589817-78c5-47ed-86b3-ff97f0feb3e7

**Review by tomoyuki-kumagai-131 — APPROVED** [review]
DALL·E 2023-11-09 14 27 31 - Create an illustration of a solemn fantasy scene inspired by a somber farewell in a mystical world, similar to the atmosphere in _Frieren at the Funer

**Review by Kohei-Sato-edash — APPROVED** [review]
LGTM

**Pull request merged**
